name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'modulos/**'
  workflow_dispatch:

env:
  IMAGE_NAME: nathanwmartins/subscription-service-java

jobs:
  # Job para execução dos testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    steps:
      # 1. Check-out do código fonte
      - uses: actions/checkout@v4

      # 2. Garantir permissão de execução do Gradle Wrapper
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 3. Configurar a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. Executar os testes da aplicação
      - name: Run application tests
        run: ./gradlew test

  # Job para buildar a aplicação
  build:
    name: Build runner
    needs: tests
    runs-on: ubuntu-latest
    steps:
      # 1. Check-out do código fonte
      - uses: actions/checkout@v4

      # 2. Garantir permissão de execução do Gradle Wrapper
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 3. Configurar a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. Valida a existência do gradle wrapper
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      # 5. Realizar o build para gerar o artefato final (sem executar testes novamente)
      - name: Build da aplicação
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build -x test

      # 6. Definir a variável BUILD_TAG com base no branch e número do run
      - name: Set BUILD_TAG
        run: |
          echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV

      # 7. Exibir a tag gerada
      - name: Print BUILD_TAG defined
        run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"

      # 8. Login no DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      # 9. Build e push da imagem Docker com a tag gerada
      - name: Build & push da imagem do docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
